Trying to update this library
seems like GHC.Integer.GMP.TypeExt was just an optimization so I got rid
of it and call GHC.Integer.GMP.XXX instead

The problem I have now is:
src/Data/BitSet/Generic.hs:111:10: error:
    • Could not deduce (Semigroup (BitSet c a))
        arising from the superclasses of an instance declaration
      from the context: Bits c
        bound by the instance declaration
        at src/Data/BitSet/Generic.hs:111:10-38
    • In the instance declaration for ‘Monoid (BitSet c a)’
    |
111 | instance Bits c => Monoid (BitSet c a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Seems like a new operation mconcat was added to Monoid ? I tried adding
one (`undefined`) to no avail.